### PR TITLE
you can recrypt history and use ssh-private key(also with passphrase) instead password

### PR DESCRIPTION
**Pull request by kinnalru**
If you specify ssh-private-key instead password gitcrypt will use it for encryption.
Actually it will use just part of private-key.
If private key is protected with passphrase - it will be requested and TEMPORARY stored in .git directory with permission 600. It will be erased after timeout(default is 30 seconds). This timeout is extended on each access to this temporary key. After timeout reached passphrase will requsted again if needed.

Also you can recrypt old repo with new feature by: "gitcrypt recrypt" and specify ~/.ssh/id_rsa or any other private key file.

Sorry for my english

### CODE REVIEW

**Comment by candeira** [comment]
Hi, thanks for this. I'll review the patch when I have a moment. However, I'm really wary of anything that stores the ssh password as text in the filesystem, even if it's "just for 30 seconds". Can't it be done without that step?

**Comment by kinnalru** [comment]
~/.ssh/id_rsa already stored in filesystem for a while, but with permissions 600 (ONLY owner can read file).

If id_rsa is not protected through the passprase - it is possible to use it without storing, but if it is protected - git will try to access this file on EACH file operation. For example when git add "file1" "file2" it try to access key for 2 times. 

This is because of git use encrypt/decrypt filter on EACH file in repo or in history(when git log -p).

**Comment by kinnalru** [comment]
I have made a little improvements - now gitcrypt takes sha512 hash from private key and use this hash like password for ecnryption(and temporary store only hash). Thus no private key contents stoted. :)

**Comment by candeira** [comment]
Hi, I'm sorry I ignored this for so long. It's not my project really, you should submit your PR to upstream, see what they think of it.

**Pull request closed without merging**
